"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "fr" | "en" | "nl";

export const languages = [
  { code: "fr" as Lang, label: "Français", flag: "🇫🇷", short: "FR" },
  { code: "en" as Lang, label: "English",  flag: "🇬🇧", short: "EN" },
  { code: "nl" as Lang, label: "Nederlands", flag: "🇳🇱", short: "NL" },
];

const translations = {
  fr: {
    // Navbar
    nav_services: "Services",
    nav_projects: "Projets",
    nav_contact: "Contact",
    nav_devis: "Devis",
    hero_eyebrow: "klinkr · Est. 2026 · Amsterdam",
    hero_line1: "VOTRE VISION.",
    hero_line2: "NOTRE CODE.",
    hero_sub: "Sites web sur-mesure pour créateurs indépendants, dirigeants et startups ambitieuses.",
    hero_cheaper: "Jusqu'à 50% moins cher.",
    hero_cta_projects: "Voir nos projets",
    hero_cta_talk: "Obtenir un devis →",
    hero_available: "Disponible pour de nouveaux projets",

    // Section labels
    label_services: "Services",
    label_projects: "Réalisations",
    label_advantages: "Avantages",
    label_technologies: "Technologies",

    // Services section
    services_title_1: "CE QUE",
    services_title_2: "NOUS",
    services_title_3: "FAISONS",
    services_sub: "De la conception à la mise en ligne, nous gérons l'intégralité de votre projet digital.",
    s1_title: "Design sur mesure",
    s1_desc: "Identités visuelles qui captivent. Chaque pixel pensé pour votre marque et vos utilisateurs.",
    s2_title: "Développement Next.js",
    s2_desc: "Sites ultra-performants avec les dernières technologies React, TypeScript et Tailwind.",
    s3_title: "Performance & SEO",
    s3_desc: "Optimisation technique pour un référencement naturel de premier rang sur Google.",
    s4_title: "Support & Maintenance",
    s4_desc: "Accompagnement continu, mises à jour de sécurité et support réactif sous 24h.",

    // Projects section
    projects_title_1: "NOS PROJETS",
    projects_title_2: "RÉCENTS",
    projects_sub: "Des expériences digitales uniques, conçues avec passion et expertise technique. Chaque projet, une nouvelle vision.",

    // Stats
    stat1_label: "Projets livrés",
    stat1_desc: "Confiés par des entrepreneurs et créateurs exigeants.",
    stat2_label: "Satisfaction client",
    stat2_desc: "Taux maintenu sur l'ensemble de nos réalisations.",
    stat3_label: "Mois d'expérience",
    stat3_desc: "Ciblée en création de sites web sur-mesure et performants.",
    stat4_label: "Support réactif",
    stat4_desc: "Délai de réponse garanti de notre équipe technique.",

    // Features section
    why_title_1: "POURQUOI",
    why_title_2: "NOUS CHOISIR",
    feat1_title: "Design moderne",
    feat1_desc: "Sites responsifs qui s'adaptent à tous les écrans.",
    feat2_title: "Performance optimisée",
    feat2_desc: "Vitesse ultrarapide et SEO naturel renforcé.",
    feat3_title: "Tarifs transparents",
    feat3_desc: "Prix justes, sans frais cachés. Devis gratuit.",
    feat4_title: "Hébergement fiable",
    feat4_desc: "99.9% de disponibilité garantie.",
    feat5_title: "Technologies modernes",
    feat5_desc: "React, Next.js, TypeScript — le meilleur de l'écosystème.",
    feat6_title: "Support dédié",
    feat6_desc: "Accompagnement personnalisé pour chaque projet.",
    feat7_title: "Maintenance incluse",
    feat7_desc: "Sécurité et mises à jour incluses 6 mois.",
    feat8_title: "Satisfaction garantie",
    feat8_desc: "Révisions illimitées jusqu'à votre satisfaction.",

    // Tech / Wobble section
    tech_title_1: "L'ÉCOSYSTÈME",
    tech_title_2: "QUE NOUS MAÎTRISONS",
    wobble1_eyebrow: "Notre philosophie",
    wobble1_h1: "On ne crée pas juste des sites.",
    wobble1_h2: "On conçoit des expériences.",
    wobble1_p: "Performance, fluidité, esthétique — dans chaque pixel, chaque interaction.",
    wobble2_eyebrow: "Portée internationale",
    wobble2_h1: "Des projets qui traversent",
    wobble2_h2: "les frontières.",
    wobble2_p: "Clients en France, Europe et au-delà.",
    wobble3_eyebrow: "Stack technologique",
    wobble3_h: "Les meilleures technologies, au service de votre vision.",
    wobble3_p: "Next.js, React, TypeScript, Sanity, Payload, Stripe, Shopify — chaque projet bénéficie de l'écosystème le plus performant du moment.",

    // CTA section
    cta_eyebrow: "Commençons",
    cta_line1: "PRÊT À",
    cta_line2: "TRANSFORMER",
    cta_line3: "VOTRE PRÉSENCE",
    cta_line4: "DIGITALE ?",
    cta_btn_main: "Démarrer mon projet",
    cta_btn_projects: "Voir les projets",

    // Marquee
    mq_design: "Design",
    mq_dev: "Développement",
    mq_perf: "Performance",
    mq_eleg: "Élégance",
    mq_innov: "Innovation",

    // Footer
    footer_desc: "Agence digitale spécialisée en développement web sur-mesure pour entrepreneurs, créateurs et startups ambitieuses.",
    footer_available: "Disponible pour de nouveaux projets",
    footer_tagline: "L'agence digitale qui transforme vos idées en expériences mémorables.",
    footer_nav_label: "Navigation",
    footer_contact_label: "Contact",
    footer_nav_services: "Services",
    footer_nav_projects: "Réalisations",
    footer_nav_contact: "Contact",
    footer_legal_mentions: "Mentions légales",
    footer_legal_privacy: "Confidentialité",
    footer_legal_cgu: "CGU",
    footer_copyright: "Tous droits réservés.",

    // Shared modal section titles
    sec_challenge: "Le défi",
    sec_solution: "Notre solution",
    sec_stack: "Stack technique",
    sec_results: "Résultats",
    see_site: "Voir le site →",

    // Project card data
    proj1_cat: "Site Web · Food Tech · Monaco",
    proj1_title: "Beldy's Club",
    proj2_cat: "Application Mobile · iOS & Android",
    proj2_title: "Beldy's App",
    proj3_cat: "Site Vitrine · Luxe · Côte d'Azur",
    proj3_title: "WelkomHome",

    // Beldy's Club modal
    beldys_hero_cap: "Un hero plein-écran qui impose Beldy's comme une référence gastronomique à Monaco — identité forte, impact immédiat.",
    beldys_shop_cap: "Menu filtré par catégories · 3 clics du choix au panier",
    beldys_order_cap: "Espace client · Suivi de commande en temps réel · Factures accessibles",
    beldys_challenge: "Beldy's Club — le réseau de restaurants premium de Monaco — n'avait aucune présence digitale unifiée. Quatre restaurants, zéro commande en ligne, et une clientèle habituée à l'excellence. Ils avaient besoin d'une plateforme qui reflète leur positionnement haut de gamme tout en étant simple et rapide à l'usage.",
    beldys_solution_p: "Nous avons conçu et développé une plateforme full-stack avec menu dynamique, panier en temps réel, paiement Stripe intégré et interface d'administration dédiée pour chaque restaurant. L'expérience utilisateur a été pensée pour mobile en priorité.",
    beldys_r1: "+35% de commandes en ligne dès le 1er mois",
    beldys_r2: "Temps moyen de commande réduit à 2 minutes",
    beldys_r3: "98% de satisfaction client — noté 4.9/5",
    beldys_r4: "4 restaurants connectés, livraison estimée <30 min",

    // Beldy's App modal
    app_overview_cap: "Vue d'ensemble de l'application — disponible sur iOS & Android.",
    app_home_cap: "Accueil · Livraison premium Monaco · Restaurants à proximité",
    app_cart_cap: "Panier · Adresse & délai affichés avant paiement · Zéro friction",
    app_challenge: "Fort du succès de la plateforme web, Beldy's Club voulait aller plus loin : une application mobile native pour iOS et Android, avec notifications push pour les promotions quotidiennes et suivi de livraison en temps réel.",
    app_solution_p: "Application React Native cross-platform déployée simultanément sur l'App Store et le Google Play Store. Géolocalisation pour afficher le restaurant le plus proche, paiement Apple Pay et Google Pay intégré en 1 tap, et notifications Expo Push pour les offres exclusives du jour.",
    app_r1: "5 000+ téléchargements en 2 mois post-lancement",
    app_r2: "Note 4.8 / 5 sur l'App Store",
    app_r3: "60% des commandes passent désormais par l'app",
    app_r4: "Taux de rétention J30 : 71%",

    // WelkomHome modal
    welkom_challenge: "Yohan & Shirley, fondateurs de WelkomHome à Saint-Tropez, proposent une sélection exclusive de villas de prestige sur la Côte d'Azur. Leur ancien site ne reflétait pas l'exclusivité de leurs propriétés et ne généraient pas assez de leads qualifiés. Ils avaient besoin d'un site qui parle d'abord aux émotions.",
    welkom_solution_p: "Site vitrine haut de gamme avec animations immersives au scroll, galerie plein-écran des villas, formulaire de contact qualifié et intégration CMS Sanity pour une autonomie totale sur les contenus. Chaque ligne de code a été pensée pour inspirer confiance et désir.",
    welkom_r1: "+40% de demandes de réservation en 3 mois",
    welkom_r2: "Taux de rebond réduit de 65% → 28%",
    welkom_r3: "Temps moyen sur le site doublé (1:20 → 3:05)",
    welkom_r4: "Top 3 Google pour 'location villa luxe Saint-Tropez'",

    // Contract page
    ctr_back: "← Retour",
    ctr_title: "Estimez votre projet",
    ctr_sub: "Configurez votre futur site et obtenez une estimation instantanée. Consultation gratuite incluse.",
    ctr_step_next: "Continuer →",
    ctr_step_prev: "← Précédent",
    ctr_step_submit: "Envoyer ma demande",
    ctr_price_label: "Estimation",
    ctr_price_from: "À partir de",
    ctr_price_note: "Devis précis après consultation gratuite de 30 min.",
    ctr_price_included: "inclus",
    ctr_price_base: "Base projet",
    ctr_price_options: "Options",
    ctr_step1_title: "Type de projet",
    ctr_step1_desc: "Quel type de site souhaitez-vous créer ?",
    ctr_step2_title: "Authentification",
    ctr_step2_desc: "Comment vos utilisateurs se connecteront-ils ?",
    ctr_step3_title: "API & Backend",
    ctr_step3_desc: "Quelle architecture backend pour votre projet ?",
    ctr_step4_title: "Base de données & Stockage",
    ctr_step4_desc: "Où et comment stocker vos données ?",
    ctr_step5_title: "Communication",
    ctr_step5_desc: "Comment interagir avec vos utilisateurs ?",
    ctr_step6_title: "Intégrations",
    ctr_step6_desc: "Quels services tiers intégrer ?",
    ctr_step7_title: "Votre demande",
    ctr_step7_desc: "Récapitulatif et envoi de votre devis",
    ctr_form_name: "Nom complet",
    ctr_form_email: "Adresse email",
    ctr_form_company: "Entreprise (optionnel)",
    ctr_form_budget: "Budget indicatif",
    ctr_form_message: "Décrivez votre projet en quelques mots",
    ctr_form_submit: "Recevoir mon devis →",
    ctr_form_success_title: "Demande envoyée !",
    ctr_form_success_sub: "Nous vous recontactons sous 24h pour votre consultation gratuite.",
    ctr_select_hint: "Sélection multiple possible",
    ctr_no_feature: "Aucune",
    ctr_summary_title: "Récapitulatif",
    ctr_summary_project: "Projet",
    ctr_summary_features: "Fonctionnalités",
    ctr_summary_empty: "Aucune option sélectionnée",
    ctr_consult_cta: "Consultation gratuite incluse",
  },
  en: {
    nav_services: "Services",
    nav_projects: "Projects",
    nav_contact: "Contact",
    nav_devis: "Quote",

    hero_eyebrow: "klinkr · Est. 2026 · Amsterdam",
    hero_line1: "YOUR VISION.",
    hero_line2: "OUR CODE.",
    hero_sub: "Tailor-made websites for independent creators, executives and ambitious startups.",
    hero_cheaper: "Up to 50% cheaper.",
    hero_cta_projects: "View our work",
    hero_cta_talk: "Get a quote →",
    hero_available: "Available for new projects",

    label_services: "Services",
    label_projects: "Projects",
    label_advantages: "Benefits",
    label_technologies: "Technologies",

    services_title_1: "WHAT",
    services_title_2: "WE",
    services_title_3: "DO",
    services_sub: "From design to launch, we handle every aspect of your digital project.",
    s1_title: "Custom Design",
    s1_desc: "Captivating visual identities. Every pixel crafted for your brand and your users.",
    s2_title: "Next.js Development",
    s2_desc: "Ultra-performant websites built with the latest React, TypeScript and Tailwind technologies.",
    s3_title: "Performance & SEO",
    s3_desc: "Technical optimization for top-tier organic ranking on Google.",
    s4_title: "Support & Maintenance",
    s4_desc: "Continuous support, security updates and reactive assistance within 24h.",

    projects_title_1: "OUR RECENT",
    projects_title_2: "PROJECTS",
    projects_sub: "Unique digital experiences, crafted with passion and technical expertise. Each project, a new vision.",

    stat1_label: "Projects delivered",
    stat1_desc: "Trusted by demanding entrepreneurs and creators.",
    stat2_label: "Client satisfaction",
    stat2_desc: "Rate maintained across all our projects.",
    stat3_label: "Months of experience",
    stat3_desc: "Focused on building custom, high-performance websites.",
    stat4_label: "Responsive support",
    stat4_desc: "Guaranteed response time from our technical team.",

    why_title_1: "WHY",
    why_title_2: "CHOOSE US",
    feat1_title: "Modern Design",
    feat1_desc: "Responsive sites that adapt to every screen.",
    feat2_title: "Optimized Performance",
    feat2_desc: "Ultra-fast speed and enhanced organic SEO.",
    feat3_title: "Transparent Pricing",
    feat3_desc: "Fair prices, no hidden fees. Free quote.",
    feat4_title: "Reliable Hosting",
    feat4_desc: "99.9% uptime guaranteed.",
    feat5_title: "Modern Technologies",
    feat5_desc: "React, Next.js, TypeScript — the best of the ecosystem.",
    feat6_title: "Dedicated Support",
    feat6_desc: "Personalized support for every project.",
    feat7_title: "Maintenance included",
    feat7_desc: "Security and updates included for 6 months.",
    feat8_title: "Satisfaction guaranteed",
    feat8_desc: "Unlimited revisions until you're satisfied.",

    tech_title_1: "THE ECOSYSTEM",
    tech_title_2: "WE MASTER",
    wobble1_eyebrow: "Our philosophy",
    wobble1_h1: "We don't just build websites.",
    wobble1_h2: "We craft experiences.",
    wobble1_p: "Performance, fluidity, aesthetics — in every pixel, every interaction.",
    wobble2_eyebrow: "International reach",
    wobble2_h1: "Projects that cross",
    wobble2_h2: "borders.",
    wobble2_p: "Clients in France, Europe and beyond.",
    wobble3_eyebrow: "Technology stack",
    wobble3_h: "The best technologies, serving your vision.",
    wobble3_p: "Next.js, React, TypeScript, Sanity, Payload, Stripe, Shopify — every project benefits from the most powerful ecosystem available.",

    cta_eyebrow: "Let's begin",
    cta_line1: "READY TO",
    cta_line2: "TRANSFORM",
    cta_line3: "YOUR DIGITAL",
    cta_line4: "PRESENCE?",
    cta_btn_main: "Start my project",
    cta_btn_projects: "View projects",

    mq_design: "Design",
    mq_dev: "Development",
    mq_perf: "Performance",
    mq_eleg: "Elegance",
    mq_innov: "Innovation",

    footer_desc: "Digital agency specialized in custom web development for entrepreneurs, creators and ambitious startups.",
    footer_available: "Available for new projects",
    footer_tagline: "The digital agency that transforms your ideas into memorable experiences.",
    footer_nav_label: "Navigation",
    footer_contact_label: "Contact",
    footer_nav_services: "Services",
    footer_nav_projects: "Projects",
    footer_nav_contact: "Contact",
    footer_legal_mentions: "Legal Notice",
    footer_legal_privacy: "Privacy",
    footer_legal_cgu: "Terms",
    footer_copyright: "All rights reserved.",

    sec_challenge: "The Challenge",
    sec_solution: "Our Solution",
    sec_stack: "Tech Stack",
    sec_results: "Results",
    see_site: "View site →",

    proj1_cat: "Website · Food Tech · Monaco",
    proj1_title: "Beldy's Club",
    proj2_cat: "Mobile App · iOS & Android",
    proj2_title: "Beldy's App",
    proj3_cat: "Showcase · Luxury · French Riviera",
    proj3_title: "WelkomHome",

    beldys_hero_cap: "A full-screen hero that establishes Beldy's as a gastronomic reference in Monaco — strong identity, immediate impact.",
    beldys_shop_cap: "Menu filtered by category · 3 clicks from choice to cart",
    beldys_order_cap: "Client space · Real-time order tracking · Invoices accessible",
    beldys_challenge: "Beldy's Club — Monaco's premium restaurant network — had no unified digital presence. Four restaurants, zero online ordering, and a clientele accustomed to excellence. They needed a platform that reflected their high-end positioning while remaining simple and fast to use.",
    beldys_solution_p: "We designed and developed a full-stack platform with a dynamic menu, real-time cart, integrated Stripe payments and a dedicated admin interface for each restaurant. The user experience was designed with mobile-first in mind.",
    beldys_r1: "+35% online orders in the first month",
    beldys_r2: "Average order time reduced to 2 minutes",
    beldys_r3: "98% client satisfaction — rated 4.9/5",
    beldys_r4: "4 restaurants connected, estimated delivery <30 min",

    app_overview_cap: "App overview — available on iOS & Android.",
    app_home_cap: "Home · Premium Monaco delivery · Nearby restaurants",
    app_cart_cap: "Cart · Address & delay shown before payment · Zero friction",
    app_challenge: "Building on the success of the web platform, Beldy's Club wanted to go further: a native mobile app for iOS and Android, with push notifications for daily promotions and real-time delivery tracking.",
    app_solution_p: "Cross-platform React Native app deployed simultaneously on the App Store and Google Play Store. Geolocation to display the nearest restaurant, Apple Pay and Google Pay integrated in 1 tap, and Expo Push notifications for exclusive daily offers.",
    app_r1: "5,000+ downloads in 2 months post-launch",
    app_r2: "Rated 4.8/5 on the App Store",
    app_r3: "60% of orders now go through the app",
    app_r4: "Day-30 retention rate: 71%",

    welkom_challenge: "Yohan & Shirley, founders of WelkomHome in Saint-Tropez, offer an exclusive selection of prestige villas on the French Riviera. Their old site didn't reflect the exclusivity of their properties and wasn't generating enough qualified leads. They needed a site that speaks to emotions first.",
    welkom_solution_p: "High-end showcase site with immersive scroll animations, full-screen villa gallery, qualified contact form and Sanity CMS integration for total content autonomy. Every line of code was designed to inspire trust and desire.",
    welkom_r1: "+40% booking requests in 3 months",
    welkom_r2: "Bounce rate reduced from 65% → 28%",
    welkom_r3: "Average time on site doubled (1:20 → 3:05)",
    welkom_r4: "Top 3 Google for 'luxury villa rental Saint-Tropez'",

    // Contract page
    ctr_back: "← Back",
    ctr_title: "Estimate your project",
    ctr_sub: "Configure your future website and get an instant estimate. Free consultation included.",
    ctr_step_next: "Continue →",
    ctr_step_prev: "← Previous",
    ctr_step_submit: "Send my request",
    ctr_price_label: "Estimate",
    ctr_price_from: "Starting from",
    ctr_price_note: "Precise quote after a free 30-min consultation.",
    ctr_price_included: "included",
    ctr_price_base: "Project base",
    ctr_price_options: "Options",
    ctr_step1_title: "Project type",
    ctr_step1_desc: "What kind of site do you want to build?",
    ctr_step2_title: "Authentication",
    ctr_step2_desc: "How will your users log in?",
    ctr_step3_title: "API & Backend",
    ctr_step3_desc: "What backend architecture for your project?",
    ctr_step4_title: "Database & Storage",
    ctr_step4_desc: "Where and how to store your data?",
    ctr_step5_title: "Communication",
    ctr_step5_desc: "How to interact with your users?",
    ctr_step6_title: "Integrations",
    ctr_step6_desc: "Which third-party services to integrate?",
    ctr_step7_title: "Your request",
    ctr_step7_desc: "Summary and submission",
    ctr_form_name: "Full name",
    ctr_form_email: "Email address",
    ctr_form_company: "Company (optional)",
    ctr_form_budget: "Indicative budget",
    ctr_form_message: "Describe your project briefly",
    ctr_form_submit: "Get my quote →",
    ctr_form_success_title: "Request sent!",
    ctr_form_success_sub: "We'll get back to you within 24h for your free consultation.",
    ctr_select_hint: "Multiple selection possible",
    ctr_no_feature: "None",
    ctr_summary_title: "Summary",
    ctr_summary_project: "Project",
    ctr_summary_features: "Features",
    ctr_summary_empty: "No options selected",
    ctr_consult_cta: "Free consultation included",
  },
  nl: {
    nav_services: "Diensten",
    nav_projects: "Projecten",
    nav_contact: "Contact",
    nav_devis: "Offerte",

    hero_eyebrow: "klinkr · Opgericht 2026 · Parijs",
    hero_line1: "UW VISIE.",
    hero_line2: "ONZE CODE.",
    hero_sub: "Maatwerk websites voor onafhankelijke makers, leidinggevenden en ambitieuze startups.",
    hero_cheaper: "Tot 50% goedkoper.",
    hero_cta_projects: "Onze projecten",
    hero_cta_talk: "Offerte aanvragen →",
    hero_available: "Beschikbaar voor nieuwe projecten",

    label_services: "Diensten",
    label_projects: "Realisaties",
    label_advantages: "Voordelen",
    label_technologies: "Technologieën",

    services_title_1: "WAT",
    services_title_2: "WIJ",
    services_title_3: "DOEN",
    services_sub: "Van ontwerp tot lancering, wij beheren elk aspect van uw digitaal project.",
    s1_title: "Maatwerk Design",
    s1_desc: "Visuele identiteiten die boeien. Elke pixel bedacht voor uw merk en uw gebruikers.",
    s2_title: "Next.js Ontwikkeling",
    s2_desc: "Ultrasnelle websites met de nieuwste React, TypeScript en Tailwind technologieën.",
    s3_title: "Prestaties & SEO",
    s3_desc: "Technische optimalisatie voor een topklassering in Google.",
    s4_title: "Support & Onderhoud",
    s4_desc: "Doorlopende begeleiding, beveiligingsupdates en reactieve ondersteuning binnen 24u.",

    projects_title_1: "ONZE RECENTE",
    projects_title_2: "PROJECTEN",
    projects_sub: "Unieke digitale ervaringen, gemaakt met passie en technische expertise. Elk project, een nieuwe visie.",

    stat1_label: "Afgeronde projecten",
    stat1_desc: "Toevertrouwd door veeleisende ondernemers en makers.",
    stat2_label: "Klanttevredenheid",
    stat2_desc: "Score gehandhaafd over al onze realisaties.",
    stat3_label: "Maanden ervaring",
    stat3_desc: "Gericht op het bouwen van maatwerk, hoogwaardige websites.",
    stat4_label: "Responsieve support",
    stat4_desc: "Gegarandeerde reactietijd van ons technisch team.",

    why_title_1: "WAAROM",
    why_title_2: "ONS KIEZEN",
    feat1_title: "Modern Design",
    feat1_desc: "Responsieve sites die zich aanpassen aan elk scherm.",
    feat2_title: "Geoptimaliseerde Prestaties",
    feat2_desc: "Ultrasnelle laadtijd en verbeterde organische SEO.",
    feat3_title: "Transparante Prijzen",
    feat3_desc: "Eerlijke prijzen, geen verborgen kosten. Gratis offerte.",
    feat4_title: "Betrouwbare Hosting",
    feat4_desc: "99,9% uptime gegarandeerd.",
    feat5_title: "Moderne Technologieën",
    feat5_desc: "React, Next.js, TypeScript — het beste van het ecosysteem.",
    feat6_title: "Toegewijde Support",
    feat6_desc: "Persoonlijke begeleiding voor elk project.",
    feat7_title: "Onderhoud inbegrepen",
    feat7_desc: "Beveiliging en updates inbegrepen voor 6 maanden.",
    feat8_title: "Tevredenheid gegarandeerd",
    feat8_desc: "Onbeperkte revisies totdat u tevreden bent.",

    tech_title_1: "HET ECOSYSTEEM",
    tech_title_2: "DAT WIJ BEHEERSEN",
    wobble1_eyebrow: "Onze filosofie",
    wobble1_h1: "We bouwen niet alleen websites.",
    wobble1_h2: "We creëren ervaringen.",
    wobble1_p: "Prestaties, vloeiendheid, esthetiek — in elke pixel, elke interactie.",
    wobble2_eyebrow: "Internationaal bereik",
    wobble2_h1: "Projecten die grenzen",
    wobble2_h2: "overschrijden.",
    wobble2_p: "Klanten in Frankrijk, Europa en daarbuiten.",
    wobble3_eyebrow: "Technologiestack",
    wobble3_h: "De beste technologieën, ten dienste van uw visie.",
    wobble3_p: "Next.js, React, TypeScript, Sanity, Payload, Stripe, Shopify — elk project profiteert van het krachtigste ecosysteem beschikbaar.",

    cta_eyebrow: "Laten we beginnen",
    cta_line1: "KLAAR OM",
    cta_line2: "UW DIGITALE",
    cta_line3: "AANWEZIGHEID",
    cta_line4: "TE TRANSFORMEREN?",
    cta_btn_main: "Mijn project starten",
    cta_btn_projects: "Projecten bekijken",

    mq_design: "Design",
    mq_dev: "Ontwikkeling",
    mq_perf: "Prestaties",
    mq_eleg: "Elegantie",
    mq_innov: "Innovatie",

    footer_desc: "Digitaal bureau gespecialiseerd in maatwerk webontwikkeling voor ondernemers, makers en ambitieuze startups.",
    footer_available: "Beschikbaar voor nieuwe projecten",
    footer_tagline: "Het digitale bureau dat uw ideeën omzet in gedenkwaardige ervaringen.",
    footer_nav_label: "Navigatie",
    footer_contact_label: "Contact",
    footer_nav_services: "Diensten",
    footer_nav_projects: "Realisaties",
    footer_nav_contact: "Contact",
    footer_legal_mentions: "Juridische Mededeling",
    footer_legal_privacy: "Privacy",
    footer_legal_cgu: "Voorwaarden",
    footer_copyright: "Alle rechten voorbehouden.",

    sec_challenge: "De uitdaging",
    sec_solution: "Onze oplossing",
    sec_stack: "Tech Stack",
    sec_results: "Resultaten",
    see_site: "Bekijk site →",

    proj1_cat: "Website · Food Tech · Monaco",
    proj1_title: "Beldy's Club",
    proj2_cat: "Mobiele App · iOS & Android",
    proj2_title: "Beldy's App",
    proj3_cat: "Showcase · Luxe · Franse Rivièra",
    proj3_title: "WelkomHome",

    beldys_hero_cap: "Een fullscreen hero die Beldy's neerzet als gastronomische referentie in Monaco — sterke identiteit, directe impact.",
    beldys_shop_cap: "Menu gefilterd op categorie · 3 klikken van keuze tot winkelwagen",
    beldys_order_cap: "Klantenruimte · Realtime ordertracking · Facturen toegankelijk",
    beldys_challenge: "Beldy's Club — het premium restaurantnetwerk van Monaco — had geen uniforme digitale aanwezigheid. Vier restaurants, nul online bestellingen, en een klantenkring gewend aan excellentie. Ze hadden een platform nodig dat hun high-end positionering weerspiegelde.",
    beldys_solution_p: "We hebben een full-stack platform ontworpen en ontwikkeld met dynamisch menu, realtime winkelwagen, geïntegreerde Stripe-betalingen en een dedicated admininterface voor elk restaurant. De gebruikerservaring werd mobile-first ontworpen.",
    beldys_r1: "+35% online bestellingen in de eerste maand",
    beldys_r2: "Gemiddelde besteltijd teruggebracht tot 2 minuten",
    beldys_r3: "98% klanttevredenheid — beoordeeld 4.9/5",
    beldys_r4: "4 restaurants verbonden, geschatte levering <30 min",

    app_overview_cap: "App-overzicht — beschikbaar op iOS & Android.",
    app_home_cap: "Home · Premium Monaco bezorging · Nabijgelegen restaurants",
    app_cart_cap: "Winkelwagen · Adres & levertijd getoond voor betaling · Nul wrijving",
    app_challenge: "Voortbouwend op het succes van het webplatform wilde Beldy's Club verder gaan: een native mobiele app voor iOS en Android, met pushmeldingen voor dagelijkse promoties en realtime bezorgtracking.",
    app_solution_p: "Cross-platform React Native app gelijktijdig uitgerold op de App Store en Google Play Store. Geolocatie voor het dichtstbijzijnde restaurant, Apple Pay en Google Pay geïntegreerd in 1 tik, en Expo Push-meldingen voor exclusieve dagelijkse aanbiedingen.",
    app_r1: "5.000+ downloads in 2 maanden na lancering",
    app_r2: "Beoordeeld 4.8/5 in de App Store",
    app_r3: "60% van de bestellingen gaat nu via de app",
    app_r4: "Dag-30 retentiepercentage: 71%",

    welkom_challenge: "Yohan & Shirley, oprichters van WelkomHome in Saint-Tropez, bieden een exclusieve selectie van prestigieuze villa's aan de Côte d'Azur. Hun oude site weerspiegelde de exclusiviteit van hun eigendommen niet en genereerde niet genoeg gekwalificeerde leads.",
    welkom_solution_p: "High-end showcase site met meeslepende scroll-animaties, fullscreen villa-galerij, gekwalificeerd contactformulier en Sanity CMS-integratie voor volledige contentvrijheid. Elke regel code is ontworpen om vertrouwen en verlangen te inspireren.",
    welkom_r1: "+40% boekingsverzoeken in 3 maanden",
    welkom_r2: "Bouncepercentage teruggebracht van 65% → 28%",
    welkom_r3: "Gemiddelde tijd op de site verdubbeld (1:20 → 3:05)",
    welkom_r4: "Top 3 Google voor 'luxe villa huren Saint-Tropez'",

    // Contract page
    ctr_back: "← Terug",
    ctr_title: "Schat uw project in",
    ctr_sub: "Configureer uw toekomstige website en krijg direct een schatting. Gratis consultatie inbegrepen.",
    ctr_step_next: "Doorgaan →",
    ctr_step_prev: "← Vorige",
    ctr_step_submit: "Mijn aanvraag sturen",
    ctr_price_label: "Schatting",
    ctr_price_from: "Vanaf",
    ctr_price_note: "Nauwkeurige offerte na gratis consultatie van 30 min.",
    ctr_price_included: "inbegrepen",
    ctr_price_base: "Projectbasis",
    ctr_price_options: "Opties",
    ctr_step1_title: "Projecttype",
    ctr_step1_desc: "Wat voor site wilt u bouwen?",
    ctr_step2_title: "Authenticatie",
    ctr_step2_desc: "Hoe loggen uw gebruikers in?",
    ctr_step3_title: "API & Backend",
    ctr_step3_desc: "Welke backend-architectuur voor uw project?",
    ctr_step4_title: "Database & Opslag",
    ctr_step4_desc: "Waar en hoe slaat u uw gegevens op?",
    ctr_step5_title: "Communicatie",
    ctr_step5_desc: "Hoe communiceert u met uw gebruikers?",
    ctr_step6_title: "Integraties",
    ctr_step6_desc: "Welke externe diensten integreren?",
    ctr_step7_title: "Uw aanvraag",
    ctr_step7_desc: "Samenvatting en indiening",
    ctr_form_name: "Volledige naam",
    ctr_form_email: "E-mailadres",
    ctr_form_company: "Bedrijf (optioneel)",
    ctr_form_budget: "Indicatief budget",
    ctr_form_message: "Beschrijf uw project kort",
    ctr_form_submit: "Mijn offerte ontvangen →",
    ctr_form_success_title: "Aanvraag verzonden!",
    ctr_form_success_sub: "We nemen binnen 24u contact op voor uw gratis consultatie.",
    ctr_select_hint: "Meerdere selecties mogelijk",
    ctr_no_feature: "Geen",
    ctr_summary_title: "Samenvatting",
    ctr_summary_project: "Project",
    ctr_summary_features: "Functies",
    ctr_summary_empty: "Geen opties geselecteerd",
    ctr_consult_cta: "Gratis consultatie inbegrepen",
  },
};

type TranslationKey = keyof typeof translations.fr;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: (key) => translations.fr[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("fr");
  const t = (key: TranslationKey): string => translations[lang][key] ?? translations.fr[key];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
